server {
  listen 80;
  server_name _;

  location / {
    proxy_pass http://frontend:80;
  }

  location /api/ {
    proxy_pass http://backend:8080/api/;
  }

  location /ai/ {
    proxy_pass http://ai:8000/;
  }

  location /health {
    proxy_pass http://backend:8080/health;
  }

  # WebSocket 추가
  location /ws-community {
    proxy_pass http://backend:8080/ws-community;
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}